language: node_js

node_js:
  - "11"
  - "10"
  - "8"
  - "6"

script:
  - npm run lint && npm run coveralls -- -c && npm run typescript

after_script:
  - ./tools/website.sh
  - npm run license-checker

notifications:
  email:
    on_success: never
    on_failure: always
